import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import AuthTest from '../components/authtest'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Hero from '../components/hero'
import AboutSection from '../components/aboutsection'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black">
        <Navbar/>
        <Hero/>
        <AboutSection />
      </main>
      <Footer />
    </div>
  )
}

export default Home
